#!/bin/bash
mkdir -p ~/.config/
mkdir -p ~/.config/nixpkgs/overlays/
mkdir -p ~/.nixpkgs/

ln -s $PWD/config/nvim $HOME/.config/nvim
ln -s $PWD/eslintrc $HOME/.eslintrc
ln -s $PWD/tmux.conf $HOME/.tmux.conf
ln -s $PWD/tmux.theme $HOME/.tmux.theme
ln -s $PWD/zshenv $HOME/.zshenv
ln -s $PWD/zshrc $HOME/.zshrc
ln -s $PWD/alacritty.toml $HOME/.alacritty.toml
ln -s $PWD/smart-switch.rb $HOME/smart-switch.rb
